sut:
  image: seegno/node:4-test
  volumes:
    - .:/app
  environment:
    - CI
  links:
    - bitcoind

bitcoind:
  image: ruimarinho/bitcoin-core:0.15.0.1-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=18333
    -rpcuser=foo
    -server
  ports:
    - 18333:18333
